name: fetch-data-1820-2020

on:
  schedule:
    - cron: '20 9 * * *'  # 18:20
  workflow_dispatch:

jobs:
  fetch-data-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Specify the Python version you need
  
    - name: Run Python script
      run: |
        sudo apt update
        sudo apt install p7zip-full
        sudo apt install curl
        pip install requests
        pip install pytz
        pip install python-telegram-bot
        python 3_GitHub_action.py
      env:
           bot_token: ${{ secrets.bot_token }}
           chat_id: ${{ secrets.chat_id }}
           duration_s: 7200


       